// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU4M7A9qobocesJxS576TtDXQDuMcmOnw',
    appId: '1:36922634622:web:02cf83f30e494eb4bd432f',
    messagingSenderId: '36922634622',
    projectId: 'img-text-editor-app',
    authDomain: 'img-text-editor-app.firebaseapp.com',
    storageBucket: 'img-text-editor-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdu2MKTg4kTUjquOvDL-7PVY9jJ40beY',
    appId: '1:36922634622:android:0346e1f77ba73aa8bd432f',
    messagingSenderId: '36922634622',
    projectId: 'img-text-editor-app',
    storageBucket: 'img-text-editor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAifojuMNnvnsfNbd1wKaNVucHEmuLPRq4',
    appId: '1:36922634622:ios:c53ca8e46f4eab9dbd432f',
    messagingSenderId: '36922634622',
    projectId: 'img-text-editor-app',
    storageBucket: 'img-text-editor-app.appspot.com',
    iosClientId: '36922634622-rki35khtm3jgsbjjvv1p8cd7kv9rv75g.apps.googleusercontent.com',
    iosBundleId: 'com.example.imageToText',
  );
}
